import Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";

const databasePath = path.resolve(process.env.DATABASE_PATH?.trim() || "./data/wiki-agent.db");
fs.mkdirSync(path.dirname(databasePath), { recursive: true });
export const db = new Database(databasePath);
db.pragma("journal_mode = WAL"); db.pragma("busy_timeout = 5000");
const exists = (name: string) => Boolean(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name));

function migrateLegacy(): void {
  if (!exists("projects")) return;
  db.pragma("foreign_keys = OFF");
  try { db.transaction(() => db.exec(`
    CREATE TABLE workspaces_new (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,type TEXT NOT NULL DEFAULT 'general',description TEXT NOT NULL,context TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',parent_workspace_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(parent_workspace_id) REFERENCES workspaces_new(id) ON DELETE CASCADE);
    INSERT INTO workspaces_new SELECT id,name,slug,CASE WHEN slug='compa-friki' THEN 'hardware_project' ELSE 'general' END,description,'',status,NULL,created_at,updated_at FROM projects;
    CREATE TABLE tasks_new (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'todo',priority TEXT NOT NULL DEFAULT 'medium',created_by TEXT NOT NULL DEFAULT 'human',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces_new(id) ON DELETE CASCADE);
    INSERT INTO tasks_new SELECT id,project_id,title,description,status,priority,created_by,created_at,updated_at FROM tasks;
    CREATE TABLE decisions_new (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,title TEXT NOT NULL,decision TEXT NOT NULL,rationale TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL DEFAULT 'human',created_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces_new(id) ON DELETE CASCADE);
    INSERT INTO decisions_new SELECT id,project_id,title,decision,rationale,created_by,created_at FROM decisions;
    CREATE TABLE knowledge_items_new (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'note',title TEXT NOT NULL,content TEXT NOT NULL,created_by TEXT NOT NULL DEFAULT 'human',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces_new(id) ON DELETE CASCADE);
    INSERT INTO knowledge_items_new SELECT id,project_id,'note',title,content,created_by,created_at,updated_at FROM notes;
    CREATE TABLE agent_runs_new (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,agent_name TEXT NOT NULL,input TEXT NOT NULL,output TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces_new(id) ON DELETE CASCADE);
    INSERT INTO agent_runs_new SELECT id,project_id,agent_name,input,output,status,created_at FROM agent_runs;
    DROP TABLE agent_runs; DROP TABLE notes; DROP TABLE decisions; DROP TABLE tasks; DROP TABLE projects;
    ALTER TABLE workspaces_new RENAME TO workspaces; ALTER TABLE tasks_new RENAME TO tasks; ALTER TABLE decisions_new RENAME TO decisions; ALTER TABLE knowledge_items_new RENAME TO knowledge_items; ALTER TABLE agent_runs_new RENAME TO agent_runs;
  `))(); } finally { db.pragma("foreign_keys = ON"); }
}

migrateLegacy();
db.exec(`
  CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,type TEXT NOT NULL DEFAULT 'general',description TEXT NOT NULL,context TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',parent_workspace_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(parent_workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'todo' CHECK(status IN ('todo','in_progress','blocked','done')),priority TEXT NOT NULL DEFAULT 'medium' CHECK(priority IN ('low','medium','high','critical')),created_by TEXT NOT NULL DEFAULT 'human',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS decisions (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,title TEXT NOT NULL,decision TEXT NOT NULL,rationale TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL DEFAULT 'human',created_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS knowledge_items (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'note' CHECK(type IN ('note','finding','question','requirement','hypothesis','reference')),title TEXT NOT NULL,content TEXT NOT NULL,created_by TEXT NOT NULL DEFAULT 'human',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS agent_runs (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,agent_name TEXT NOT NULL,input TEXT NOT NULL,output TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS workspace_briefings (workspace_id TEXT PRIMARY KEY,current_focus TEXT NOT NULL,recent_changes_json TEXT NOT NULL,blockers_json TEXT NOT NULL,pending_review_json TEXT NOT NULL,suggested_next_action TEXT NOT NULL,generated_at TEXT NOT NULL,agent_run_id TEXT,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,FOREIGN KEY(agent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL);
  CREATE TABLE IF NOT EXISTS resident_analyses (workspace_id TEXT NOT NULL,mode TEXT NOT NULL CHECK(mode IN ('overview','tasks','decisions','knowledge','activity')),sections_json TEXT NOT NULL,generated_at TEXT NOT NULL,source_last_activity_at TEXT,agent_run_id TEXT,PRIMARY KEY(workspace_id,mode),FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,FOREIGN KEY(agent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL);
  CREATE TABLE IF NOT EXISTS activity_events (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,actor TEXT NOT NULL,source TEXT NOT NULL,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,summary TEXT NOT NULL,metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS decision_proposals (id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,title TEXT NOT NULL,proposed_decision TEXT NOT NULL,rationale TEXT NOT NULL DEFAULT '',proposed_by TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),reviewed_by TEXT,reviewed_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS repository_imports (id TEXT PRIMARY KEY,repository_url TEXT NOT NULL,owner TEXT NOT NULL,repository_name TEXT NOT NULL,default_branch TEXT NOT NULL,commit_sha TEXT NOT NULL,additional_context TEXT NOT NULL DEFAULT '',status TEXT NOT NULL CHECK(status IN ('analyzing','pending','confirmed','failed')),repository_json TEXT NOT NULL DEFAULT '{}',preview_json TEXT NOT NULL DEFAULT '{}',metrics_json TEXT NOT NULL DEFAULT '{}',error TEXT,workspace_id TEXT,created_at TEXT NOT NULL,confirmed_at TEXT,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE SET NULL);
  CREATE TABLE IF NOT EXISTS import_provenance (id TEXT PRIMARY KEY,import_id TEXT NOT NULL,workspace_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,source_url TEXT NOT NULL,source_path TEXT,commit_sha TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(import_id) REFERENCES repository_imports(id) ON DELETE CASCADE,FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS session_items (id INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,item_json TEXT NOT NULL,created_at TEXT NOT NULL);
  CREATE INDEX IF NOT EXISTS idx_workspaces_parent ON workspaces(parent_workspace_id); CREATE INDEX IF NOT EXISTS idx_tasks_workspace ON tasks(workspace_id); CREATE INDEX IF NOT EXISTS idx_decisions_workspace ON decisions(workspace_id); CREATE INDEX IF NOT EXISTS idx_knowledge_workspace ON knowledge_items(workspace_id); CREATE INDEX IF NOT EXISTS idx_runs_workspace ON agent_runs(workspace_id); CREATE INDEX IF NOT EXISTS idx_activity_workspace ON activity_events(workspace_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_proposals_workspace ON decision_proposals(workspace_id,status,created_at DESC); CREATE INDEX IF NOT EXISTS idx_imports_status ON repository_imports(status,created_at DESC); CREATE INDEX IF NOT EXISTS idx_provenance_import ON import_provenance(import_id); CREATE INDEX IF NOT EXISTS idx_session_items_session ON session_items(session_id,id);
`);
const importColumns=exists("repository_imports")?db.prepare("PRAGMA table_info(repository_imports)").all() as Array<{name:string}>:[];
if(importColumns.length&&!importColumns.some(column=>column.name==="additional_context"))db.exec("ALTER TABLE repository_imports ADD COLUMN additional_context TEXT NOT NULL DEFAULT ''");
db.pragma("foreign_keys = ON");
const now = () => new Date().toISOString(); const id = (p: string) => `${p}_${randomUUID()}`;

export function seedDatabase(): void {
  db.transaction(() => {
    const ts=now(), insertWorkspace=db.prepare("INSERT INTO workspaces VALUES (?,?,?,?,?,?,?,?,?,?)"), task=db.prepare("INSERT INTO tasks VALUES (?,?,?,?,?,?,?,?,?)"), decision=db.prepare("INSERT INTO decisions VALUES (?,?,?,?,?,?,?)"), knowledge=db.prepare("INSERT INTO knowledge_items VALUES (?,?,?,?,?,?,?,?)");
    if(!db.prepare("SELECT 1 FROM workspaces WHERE slug='lockerboard'").get()){
      const wid="workspace_lockerboard";insertWorkspace.run(wid,"LockerBoard","lockerboard","software_project","A multi-tenant sports achievement platform with team spaces, player profiles, achievement catalogs, rankings and invitation flows.","Multi-tenant product delivery, team membership and invitation flows.","active",null,ts,ts);
      task.run(id("task"),wid,"Implement invitation expiration","Add expiration, single-use consumption and resend constraints to invitation tokens.","in_progress","high","human",ts,ts);task.run(id("task"),wid,"Define achievement award permissions","Specify which roles can award each achievement and record the awarding actor.","todo","high","human",ts,ts);task.run(id("task"),wid,"Finalize mobile dashboard","Complete responsive dashboard interaction and layout for coaches and players.","todo","medium","human",ts,ts);task.run(id("task"),wid,"Design team onboarding flow","Define the first-run flow for creating a team, inviting members and choosing a sport.","todo","high","human",ts,ts);task.run(id("task"),wid,"Add ranking filters","Support season, team and achievement-category filters without changing the default ranking.","todo","medium","human",ts,ts);task.run(id("task"),wid,"Define privacy controls for player profiles","Document visibility rules for names, avatars, statistics and achievement history.","blocked","high","human",ts,ts);task.run(id("task"),wid,"Add audit trail for admin actions","Record membership, permission and achievement changes for support and accountability.","todo","medium","human",ts,ts);task.run(id("task"),wid,"Create end-to-end invitation tests","Cover expired, reused, revoked and successfully accepted invitations.","todo","medium","human",ts,ts);
      decision.run(id("decision"),wid,"Multi-tenant team model","TeamMembership connects users to teams and stores their role.","Users may participate in more than one team.","human",ts);decision.run(id("decision"),wid,"Invitation tokens are single-use","An accepted invitation cannot be replayed and expired tokens are rejected.","This limits accidental duplicate membership and reduces abuse.","human",ts);decision.run(id("decision"),wid,"Rankings are scoped by season","The product keeps historical seasons separate from the current competition.","Coaches need current rankings without losing previous results.","human",ts);
      knowledge.run(id("knowledge"),wid,"requirement","Invitation flow","Players join a team through an invitation token with expiration, revocation and single-use constraints.","human",ts,ts);knowledge.run(id("knowledge"),wid,"requirement","Role model","Team owners and coaches manage rosters and achievements; players can view their own progress and public team rankings.","human",ts,ts);knowledge.run(id("knowledge"),wid,"question","Player privacy","Confirm whether player statistics are visible publicly, only to team members, or configurable per team.","human",ts,ts);knowledge.run(id("knowledge"),wid,"reference","Product slice","The first valuable release is team onboarding, roster management, achievement awarding and a season ranking view.","human",ts,ts);
    }
    if(!db.prepare("SELECT 1 FROM workspaces WHERE slug='esigglol'").get()){
      const wid="workspace_esigglol";insertWorkspace.run(wid,"esigglol","esigglol","software_project","A League of Legends tournament platform with Riot integration, team management, brackets, live results and public rankings.","Production hardening, tournament operations and player-facing experience.","active",null,ts,ts);
      const imported=[
        [62,"Indicación de timezone en scheduledAt","enhancement,baja"],[61,"Reset de tournament config desde la UI","enhancement,baja"],[59,"Refresh de stats de jugador individual","enhancement,media"],[32,"Extraer constantes mágicas a configuración (delays, batch sizes, TTLs)","baja"],[31,"Notificaciones en tiempo real cuando Riot envía callback de resultado","baja"],[30,"Tournament codes: validar expiración y permitir regeneración","baja,incompleto"],[29,"Shutdown graceful: manejar SIGTERM para esperar jobs en curso","baja"],[26,"Accesibilidad: auditar contraste de colores (dark theme)","baja"],[23,"SEO: crear robots.txt y sitemap.xml","baja"],[22,"Cachear resultados de screenshot parsing para evitar costes duplicados","media"],[21,"ANTHROPIC_API_KEY: deshabilitar botón de parse-screenshot en UI si no está configurada","media"],[18,"Añadir timeout a las llamadas fetch de lib/riot.ts","media"],[17,"Cachear getTeams/getPhases a nivel servidor para evitar deserializar JSON en cada request","media"],[16,"Evaluar ISR (Incremental Static Regeneration) para páginas públicas","media"],[15,"Lint en pre-commit hook (husky + lint-staged)","media"],[14,"Tests E2E para flujos críticos (generación de bracket, actualización de resultados)","media"],[11,"Integrar Sentry para error tracking","media"],[9,"Estado en memoria (isRunning, rate limiting) → Redis si múltiples réplicas","alta"],[6,"Configurar backups automáticos de SQLite (cron + storage externo)","alta"],[5,"Implementar sistema de migraciones de DB (schema versionado)","alta"],[4,"Migrar Tournament API de stub a produccion (tournament-stub-v5 → tournament/v5)","critico"],[2,"Usar gestor de secretos en produccion en lugar de .env.local","critico"],[1,"Rotar API keys y generar SESSION_SECRET seguro","critico"]] as const;
      for(const [number,title,labels] of imported){const priority=labels.includes("critico")?"critical":labels.includes("alta")?"high":labels.includes("media")?"medium":"low";const status=number===4||number===2||number===1?"blocked":"todo";task.run(`task_esigglol_${number}`,wid,`#${number} ${title}`,`Hardcoded seed entry based on https://github.com/JavierLoro/esigglol/issues/${number}. GitHub labels: ${labels}. This was not created by the Import Agent.`,status,priority,"system",ts,ts)}
      knowledge.run(id("knowledge"),wid,"finding","Production readiness signals","The hardcoded seed backlog contains three critical issues (#4, #2 and #1) related to Tournament API production access and secret management. This is an evidence-based finding from GitHub issues, not a confirmed human decision.","system",ts,ts);knowledge.run(id("knowledge"),wid,"reference","Seeded GitHub backlog (not an agent import)","23 open issues from JavierLoro/esigglol are embedded in the demo seed as realistic sample tasks. They retain issue numbers, labels and source URLs, but no repository_imports or import_provenance records are created until the Import Agent actually analyzes and a human confirms an import.","system",ts,ts);knowledge.run(id("knowledge"),wid,"question","Production access","Confirm Riot Tournament API production access, secret rotation and deployment topology before closing the critical blockers.","human",ts,ts);
    }
  })();
}
export function resetDatabase(): void { db.transaction(() => db.exec("DELETE FROM session_items;DELETE FROM import_provenance;DELETE FROM repository_imports;DELETE FROM activity_events;DELETE FROM resident_analyses;DELETE FROM workspace_briefings;DELETE FROM decision_proposals;DELETE FROM agent_runs;DELETE FROM knowledge_items;DELETE FROM decisions;DELETE FROM tasks;DELETE FROM workspaces;"))(); seedDatabase(); backfillActivity(); }
seedDatabase();

function backfillActivity(): void {
  const {count}=db.prepare("SELECT COUNT(*) count FROM activity_events").get() as {count:number};if(count)return;
  const insert=db.prepare("INSERT INTO activity_events (id,workspace_id,actor,source,action,entity_type,entity_id,summary,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)");
  db.transaction(()=>{
    for(const row of db.prepare("SELECT * FROM tasks").all() as Array<Record<string,string>>)insert.run(id("activity"),row.workspace_id,row.created_by,"system","task_created","task",row.id,`Created task \"${row.title}\"`,JSON.stringify({priority:row.priority,status:row.status}),row.created_at);
    for(const row of db.prepare("SELECT * FROM decisions").all() as Array<Record<string,string>>)insert.run(id("activity"),row.workspace_id,row.created_by,"system","decision_added","decision",row.id,`Added decision \"${row.title}\"`,"{}",row.created_at);
    for(const row of db.prepare("SELECT * FROM knowledge_items").all() as Array<Record<string,string>>)insert.run(id("activity"),row.workspace_id,row.created_by,"system","knowledge_added","knowledge",row.id,`Added ${row.type} \"${row.title}\"`,JSON.stringify({type:row.type}),row.created_at);
    for(const row of db.prepare("SELECT * FROM agent_runs").all() as Array<Record<string,string>>)insert.run(id("activity"),row.workspace_id,row.agent_name,"system",row.status==="completed"?"agent_run_completed":"agent_run_failed","agent_run",row.id,`${row.status==="completed"?"Completed":"Failed"} agent run`,JSON.stringify({prompt:row.input}),row.created_at);
  })();
}
backfillActivity();
