import { randomUUID } from "node:crypto";
import { db } from "./db.js";
export type TaskStatus="todo"|"in_progress"|"blocked"|"done"; export type TaskPriority="low"|"medium"|"high"|"critical"; export type KnowledgeType="note"|"finding"|"question"|"requirement"|"hypothesis"|"reference";
export interface Workspace { id:string;name:string;slug:string;type:string;description:string;context:string;status:string;parent_workspace_id:string|null;created_at:string;updated_at:string }
export interface WorkspaceSummary extends Workspace { open_task_count:number; child_count:number }
export interface ProjectTask { id:string;workspace_id:string;title:string;description:string;status:TaskStatus;priority:TaskPriority;created_by:string;created_at:string;updated_at:string }
export interface Decision { id:string;workspace_id:string;title:string;decision:string;rationale:string;created_by:string;created_at:string }
export interface KnowledgeItem { id:string;workspace_id:string;type:KnowledgeType;title:string;content:string;created_by:string;created_at:string;updated_at:string }
export interface AgentRun { id:string;workspace_id:string;agent_name:string;input:string;output:string;status:string;created_at:string }
export interface ActivityItem { id:string;workspace_id:string;actor:string;action:"task_created"|"decision_added"|"knowledge_added"|"agent_run";detail:string;created_at:string }
export class NotFoundError extends Error { readonly statusCode=404 }
const now=()=>new Date().toISOString(), id=(p:string)=>`${p}_${randomUUID()}`;
export const listWorkspaces=()=>db.prepare(`SELECT w.*,(SELECT COUNT(*) FROM tasks t WHERE t.workspace_id=w.id AND t.status!='done') open_task_count,(SELECT COUNT(*) FROM workspaces c WHERE c.parent_workspace_id=w.id) child_count FROM workspaces w ORDER BY w.parent_workspace_id IS NOT NULL,w.created_at`).all() as WorkspaceSummary[];
export const getDefaultWorkspace=()=>db.prepare("SELECT * FROM workspaces WHERE parent_workspace_id IS NULL ORDER BY created_at LIMIT 1").get() as Workspace|undefined;
export const getWorkspace=(value:string)=>db.prepare("SELECT * FROM workspaces WHERE id=? OR slug=? LIMIT 1").get(value,value) as Workspace|undefined;
function requireWorkspace(value:string){const w=getWorkspace(value);if(!w)throw new NotFoundError("Workspace not found.");return w}
export const listChildren=(wid:string)=>{requireWorkspace(wid);return db.prepare("SELECT * FROM workspaces WHERE parent_workspace_id=? ORDER BY name").all(wid) as Workspace[]};
export const listTasks=(wid:string)=>db.prepare(`SELECT * FROM tasks WHERE workspace_id=? ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,created_at DESC`).all(wid) as ProjectTask[];
export const listDecisions=(wid:string)=>db.prepare("SELECT * FROM decisions WHERE workspace_id=? ORDER BY created_at DESC").all(wid) as Decision[];
export const listKnowledge=(wid:string)=>db.prepare("SELECT * FROM knowledge_items WHERE workspace_id=? ORDER BY updated_at DESC").all(wid) as KnowledgeItem[];
export const listAgentRuns=(wid:string)=>db.prepare("SELECT * FROM agent_runs WHERE workspace_id=? ORDER BY created_at DESC LIMIT 20").all(wid) as AgentRun[];
export function getActivity(wid:string,limit=50):ActivityItem[]{requireWorkspace(wid);return db.prepare(`SELECT * FROM (SELECT id,workspace_id,created_by actor,'task_created' action,title detail,created_at FROM tasks WHERE workspace_id=? UNION ALL SELECT id,workspace_id,created_by,'decision_added',title,created_at FROM decisions WHERE workspace_id=? UNION ALL SELECT id,workspace_id,created_by,'knowledge_added',title,created_at FROM knowledge_items WHERE workspace_id=? UNION ALL SELECT id,workspace_id,agent_name,'agent_run',CASE WHEN status='completed' THEN input ELSE status||': '||input END,created_at FROM agent_runs WHERE workspace_id=?) ORDER BY created_at DESC LIMIT ?`).all(wid,wid,wid,wid,limit) as ActivityItem[]}
export function getWorkspaceContext(value:string){const workspace=requireWorkspace(value),wid=workspace.id;return{workspace,tasks:listTasks(wid),decisions:listDecisions(wid),knowledge:listKnowledge(wid),agentRuns:listAgentRuns(wid),activity:getActivity(wid),children:listChildren(wid)}}
export function createTask(input:{workspaceId:string;title:string;description?:string;priority?:TaskPriority;status?:TaskStatus;createdBy?:string}){const w=requireWorkspace(input.workspaceId),taskId=id("task"),ts=now();db.prepare("INSERT INTO tasks VALUES (?,?,?,?,?,?,?,?,?)").run(taskId,w.id,input.title,input.description??"",input.status??"todo",input.priority??"medium",input.createdBy??"human",ts,ts);return db.prepare("SELECT * FROM tasks WHERE id=?").get(taskId) as ProjectTask}
export function updateTask(taskId:string,c:{title?:string;description?:string;priority?:TaskPriority;status?:TaskStatus}){const old=db.prepare("SELECT * FROM tasks WHERE id=?").get(taskId) as ProjectTask|undefined;if(!old)throw new NotFoundError("Task not found.");db.prepare("UPDATE tasks SET title=?,description=?,priority=?,status=?,updated_at=? WHERE id=?").run(c.title??old.title,c.description??old.description,c.priority??old.priority,c.status??old.status,now(),taskId);return db.prepare("SELECT * FROM tasks WHERE id=?").get(taskId) as ProjectTask}
export function addDecision(input:{workspaceId:string;title:string;decision:string;rationale?:string;createdBy?:string}){const w=requireWorkspace(input.workspaceId),did=id("decision");db.prepare("INSERT INTO decisions VALUES (?,?,?,?,?,?,?)").run(did,w.id,input.title,input.decision,input.rationale??"",input.createdBy??"human",now());return db.prepare("SELECT * FROM decisions WHERE id=?").get(did) as Decision}
export function addKnowledge(input:{workspaceId:string;type?:KnowledgeType;title:string;content:string;createdBy?:string}){const w=requireWorkspace(input.workspaceId),kid=id("knowledge"),ts=now();db.prepare("INSERT INTO knowledge_items VALUES (?,?,?,?,?,?,?,?)").run(kid,w.id,input.type??"note",input.title,input.content,input.createdBy??"human",ts,ts);return db.prepare("SELECT * FROM knowledge_items WHERE id=?").get(kid) as KnowledgeItem}
export function createAgentRun(input:{workspaceId:string;agentName:string;prompt:string;output:string;status:string}){const w=requireWorkspace(input.workspaceId),rid=id("run");db.prepare("INSERT INTO agent_runs VALUES (?,?,?,?,?,?,?)").run(rid,w.id,input.agentName,input.prompt,input.output,input.status,now());return rid}
