import { randomUUID } from "node:crypto";
import { db } from "./db.js";
export type TaskStatus="todo"|"in_progress"|"blocked"|"done"; export type TaskPriority="low"|"medium"|"high"|"critical"; export type KnowledgeType="note"|"finding"|"question"|"requirement"|"hypothesis"|"reference"; export type ActivitySource="human"|"webmcp"|"wiki_agent"|"system"; export type WorkspaceType="general"|"software_project"|"hardware_project"|"research"|"organization"|"event";
export interface Workspace{id:string;name:string;slug:string;type:string;description:string;context:string;status:string;parent_workspace_id:string|null;created_at:string;updated_at:string} export interface WorkspaceSummary extends Workspace{open_task_count:number;child_count:number}
export interface ProjectTask{id:string;workspace_id:string;title:string;description:string;status:TaskStatus;priority:TaskPriority;created_by:string;created_at:string;updated_at:string} export interface Decision{id:string;workspace_id:string;title:string;decision:string;rationale:string;created_by:string;created_at:string} export interface KnowledgeItem{id:string;workspace_id:string;type:KnowledgeType;title:string;content:string;created_by:string;created_at:string;updated_at:string} export interface AgentRun{id:string;workspace_id:string;agent_name:string;input:string;output:string;status:string;created_at:string}
export interface ActivityEvent{id:string;workspace_id:string;actor:string;source:ActivitySource;action:string;entity_type:string;entity_id:string|null;summary:string;metadata_json:string;created_at:string}
export interface DecisionProposal{id:string;workspace_id:string;title:string;proposed_decision:string;rationale:string;proposed_by:string;status:"pending"|"approved"|"rejected";reviewed_by:string|null;reviewed_at:string|null;created_at:string}
export interface WorkspaceBriefing{workspace_id:string;current_focus:string;recent_changes:string[];blockers:string[];pending_review:string[];suggested_next_action:string;generated_at:string;agent_run_id:string|null}
export class NotFoundError extends Error{readonly statusCode=404} export class ConflictError extends Error{readonly statusCode=409}
const now=()=>new Date().toISOString(),id=(p:string)=>`${p}_${randomUUID()}`;
function slugify(name:string):string{return name.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"workspace"}
export function getWorkspace(value:string){return db.prepare("SELECT * FROM workspaces WHERE id=? OR slug=? LIMIT 1").get(value,value) as Workspace|undefined} function requireWorkspace(value:string){const w=getWorkspace(value);if(!w)throw new NotFoundError("Workspace not found.");return w}
export const getDefaultWorkspace=()=>db.prepare("SELECT * FROM workspaces WHERE parent_workspace_id IS NULL ORDER BY created_at LIMIT 1").get() as Workspace|undefined;
export const listWorkspaces=()=>db.prepare(`SELECT w.*,(SELECT COUNT(*) FROM tasks t WHERE t.workspace_id=w.id AND t.status!='done') open_task_count,(SELECT COUNT(*) FROM workspaces c WHERE c.parent_workspace_id=w.id) child_count FROM workspaces w ORDER BY w.parent_workspace_id IS NOT NULL,w.created_at`).all() as WorkspaceSummary[];
export const listChildren=(value:string)=>{const w=requireWorkspace(value);return db.prepare("SELECT * FROM workspaces WHERE parent_workspace_id=? ORDER BY name").all(w.id) as Workspace[]};
export const listTasks=(wid:string)=>db.prepare(`SELECT * FROM tasks WHERE workspace_id=? ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,created_at DESC`).all(wid) as ProjectTask[]; export const listDecisions=(wid:string)=>db.prepare("SELECT * FROM decisions WHERE workspace_id=? ORDER BY created_at DESC").all(wid) as Decision[]; export const listKnowledge=(wid:string)=>db.prepare("SELECT * FROM knowledge_items WHERE workspace_id=? ORDER BY updated_at DESC").all(wid) as KnowledgeItem[]; export const listAgentRuns=(wid:string)=>db.prepare("SELECT * FROM agent_runs WHERE workspace_id=? ORDER BY created_at DESC LIMIT 20").all(wid) as AgentRun[];
export function recordActivity(input:{workspaceId:string;actor:string;source:ActivitySource;action:string;entityType:string;entityId?:string|null;summary:string;metadata?:Record<string,unknown>;createdAt?:string}):ActivityEvent{const w=requireWorkspace(input.workspaceId),aid=id("activity");db.prepare("INSERT INTO activity_events VALUES (?,?,?,?,?,?,?,?,?,?)").run(aid,w.id,input.actor,input.source,input.action,input.entityType,input.entityId??null,input.summary,JSON.stringify(input.metadata??{}),input.createdAt??now());return db.prepare("SELECT * FROM activity_events WHERE id=?").get(aid) as ActivityEvent}
export function getActivity(value:string,limit=50){const w=requireWorkspace(value);return db.prepare("SELECT * FROM activity_events WHERE workspace_id=? ORDER BY created_at DESC LIMIT ?").all(w.id,limit) as ActivityEvent[]}
export function listDecisionProposals(value:string,status?:DecisionProposal["status"]){const w=requireWorkspace(value);return(status?db.prepare("SELECT * FROM decision_proposals WHERE workspace_id=? AND status=? ORDER BY created_at DESC").all(w.id,status):db.prepare("SELECT * FROM decision_proposals WHERE workspace_id=? ORDER BY created_at DESC").all(w.id)) as DecisionProposal[]}
export function getWorkspaceBriefing(value:string):WorkspaceBriefing|null{const w=requireWorkspace(value),row=db.prepare("SELECT * FROM workspace_briefings WHERE workspace_id=?").get(w.id) as Record<string,string|null>|undefined;if(!row)return null;return{workspace_id:String(row.workspace_id),current_focus:String(row.current_focus),recent_changes:JSON.parse(String(row.recent_changes_json)) as string[],blockers:JSON.parse(String(row.blockers_json)) as string[],pending_review:JSON.parse(String(row.pending_review_json)) as string[],suggested_next_action:String(row.suggested_next_action),generated_at:String(row.generated_at),agent_run_id:row.agent_run_id}}
export function getWorkspaceContext(value:string){const w=requireWorkspace(value);return{workspace:w,tasks:listTasks(w.id),decisions:listDecisions(w.id),knowledge:listKnowledge(w.id),decisionProposals:listDecisionProposals(w.id),agentRuns:listAgentRuns(w.id),activity:getActivity(w.id),children:listChildren(w.id),briefing:getWorkspaceBriefing(w.id)}}
export function createWorkspace(input:{name:string;type:WorkspaceType;description?:string;context?:string}):Workspace{return db.transaction(()=>{const base=slugify(input.name);let slug=base,suffix=2;while(db.prepare("SELECT 1 FROM workspaces WHERE slug=?").get(slug)){slug=`${base.slice(0,Math.max(1,80-String(suffix).length-1))}-${suffix++}`}const wid=id("workspace"),ts=now(),description=input.description??"",context=input.context??description;db.prepare("INSERT INTO workspaces (id,name,slug,type,description,context,status,parent_workspace_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(wid,input.name,slug,input.type,description,context,"active",null,ts,ts);recordActivity({workspaceId:wid,actor:"human",source:"human",action:"workspace_created",entityType:"workspace",entityId:wid,summary:`Created workspace \"${input.name}\"`});return db.prepare("SELECT * FROM workspaces WHERE id=?").get(wid) as Workspace}).immediate()}
type Attribution={createdBy?:string;source?:ActivitySource};
export function createTask(input:{workspaceId:string;title:string;description?:string;priority?:TaskPriority;status?:TaskStatus}&Attribution){const w=requireWorkspace(input.workspaceId),tid=id("task"),ts=now(),actor=input.createdBy??"human",source=input.source??"human";db.transaction(()=>{db.prepare("INSERT INTO tasks VALUES (?,?,?,?,?,?,?,?,?)").run(tid,w.id,input.title,input.description??"",input.status??"todo",input.priority??"medium",actor,ts,ts);recordActivity({workspaceId:w.id,actor,source,action:"task_created",entityType:"task",entityId:tid,summary:`Created task \"${input.title}\"`,metadata:{priority:input.priority??"medium",status:input.status??"todo"}})})();return db.prepare("SELECT * FROM tasks WHERE id=?").get(tid) as ProjectTask}
export function updateTask(taskId:string,input:{title?:string;description?:string;priority?:TaskPriority;status?:TaskStatus;actor?:string;source?:ActivitySource}){const old=db.prepare("SELECT * FROM tasks WHERE id=?").get(taskId) as ProjectTask|undefined;if(!old)throw new NotFoundError("Task not found.");const changes:Record<string,{from:string;to:string}>={};for(const key of ["title","description","priority","status"] as const){const value=input[key];if(value!==undefined&&value!==old[key])changes[key]={from:old[key],to:value}}if(!Object.keys(changes).length)return old;db.transaction(()=>{db.prepare("UPDATE tasks SET title=?,description=?,priority=?,status=?,updated_at=? WHERE id=?").run(input.title??old.title,input.description??old.description,input.priority??old.priority,input.status??old.status,now(),taskId);recordActivity({workspaceId:old.workspace_id,actor:input.actor??"human",source:input.source??"human",action:"task_updated",entityType:"task",entityId:taskId,summary:`Updated task \"${input.title??old.title}\"`,metadata:{changes}})})();return db.prepare("SELECT * FROM tasks WHERE id=?").get(taskId) as ProjectTask}
export function addDecision(input:{workspaceId:string;title:string;decision:string;rationale?:string}&Attribution){const w=requireWorkspace(input.workspaceId),did=id("decision"),actor=input.createdBy??"human";db.transaction(()=>{db.prepare("INSERT INTO decisions VALUES (?,?,?,?,?,?,?)").run(did,w.id,input.title,input.decision,input.rationale??"",actor,now());recordActivity({workspaceId:w.id,actor,source:input.source??"human",action:"decision_added",entityType:"decision",entityId:did,summary:`Added decision \"${input.title}\"`})})();return db.prepare("SELECT * FROM decisions WHERE id=?").get(did) as Decision}
export function addKnowledge(input:{workspaceId:string;type?:KnowledgeType;title:string;content:string}&Attribution){const w=requireWorkspace(input.workspaceId),kid=id("knowledge"),ts=now(),actor=input.createdBy??"human",type=input.type??"note";db.transaction(()=>{db.prepare("INSERT INTO knowledge_items VALUES (?,?,?,?,?,?,?,?)").run(kid,w.id,type,input.title,input.content,actor,ts,ts);recordActivity({workspaceId:w.id,actor,source:input.source??"human",action:"knowledge_added",entityType:"knowledge",entityId:kid,summary:`Added ${type} \"${input.title}\"`,metadata:{type}})})();return db.prepare("SELECT * FROM knowledge_items WHERE id=?").get(kid) as KnowledgeItem}
export function createDecisionProposal(input:{workspaceId:string;title:string;decision:string;rationale?:string;proposedBy?:string;source?:ActivitySource}){const w=requireWorkspace(input.workspaceId),pid=id("proposal"),actor=input.proposedBy??"webmcp-agent",ts=now();db.transaction(()=>{db.prepare("INSERT INTO decision_proposals VALUES (?,?,?,?,?,?,?,?,?,?)").run(pid,w.id,input.title,input.decision,input.rationale??"",actor,"pending",null,null,ts);recordActivity({workspaceId:w.id,actor,source:input.source??"webmcp",action:"decision_proposed",entityType:"decision_proposal",entityId:pid,summary:`Proposed decision \"${input.title}\"`})})();return db.prepare("SELECT * FROM decision_proposals WHERE id=?").get(pid) as DecisionProposal}
function requirePending(proposalId:string){const p=db.prepare("SELECT * FROM decision_proposals WHERE id=?").get(proposalId) as DecisionProposal|undefined;if(!p)throw new NotFoundError("Decision proposal not found.");if(p.status!=="pending")throw new ConflictError(`Decision proposal has already been ${p.status}.`);return p}
export function approveDecisionProposal(proposalId:string,input:{reviewedBy?:string;source?:ActivitySource}={}){const reviewer=input.reviewedBy??"human",did=id("decision"),ts=now();return db.transaction(()=>{const p=requirePending(proposalId);db.prepare("INSERT INTO decisions VALUES (?,?,?,?,?,?,?)").run(did,p.workspace_id,p.title,p.proposed_decision,p.rationale,reviewer,ts);db.prepare("UPDATE decision_proposals SET status='approved',reviewed_by=?,reviewed_at=? WHERE id=?").run(reviewer,ts,p.id);recordActivity({workspaceId:p.workspace_id,actor:reviewer,source:input.source??"human",action:"decision_approved",entityType:"decision",entityId:did,summary:`Approved decision \"${p.title}\"`,metadata:{proposalId:p.id,proposedBy:p.proposed_by}});return{proposal:db.prepare("SELECT * FROM decision_proposals WHERE id=?").get(p.id) as DecisionProposal,decision:db.prepare("SELECT * FROM decisions WHERE id=?").get(did) as Decision}})()}
export function rejectDecisionProposal(proposalId:string,input:{reviewedBy?:string;source?:ActivitySource}={}){const reviewer=input.reviewedBy??"human",ts=now();return db.transaction(()=>{const p=requirePending(proposalId);db.prepare("UPDATE decision_proposals SET status='rejected',reviewed_by=?,reviewed_at=? WHERE id=?").run(reviewer,ts,p.id);recordActivity({workspaceId:p.workspace_id,actor:reviewer,source:input.source??"human",action:"decision_rejected",entityType:"decision_proposal",entityId:p.id,summary:`Rejected decision \"${p.title}\"`,metadata:{proposedBy:p.proposed_by}});return db.prepare("SELECT * FROM decision_proposals WHERE id=?").get(p.id) as DecisionProposal})()}
export function createAgentRun(input:{workspaceId:string;agentName:string;prompt:string;output:string;status:string}){const w=requireWorkspace(input.workspaceId),rid=id("run"),ts=now(),completed=input.status==="completed";db.transaction(()=>{db.prepare("INSERT INTO agent_runs VALUES (?,?,?,?,?,?,?)").run(rid,w.id,input.agentName,input.prompt,input.output,input.status,ts);recordActivity({workspaceId:w.id,actor:input.agentName,source:"wiki_agent",action:completed?"agent_run_completed":"agent_run_failed",entityType:"agent_run",entityId:rid,summary:`${completed?"Completed":"Failed"} agent run`,metadata:{prompt:input.prompt}})})();return rid}
export function saveWorkspaceBriefing(input:{workspaceId:string;currentFocus:string;recentChanges:string[];blockers:string[];pendingReview:string[];suggestedNextAction:string}){const w=requireWorkspace(input.workspaceId),rid=id("run"),ts=now(),output=JSON.stringify({currentFocus:input.currentFocus,recentChanges:input.recentChanges,blockers:input.blockers,pendingReview:input.pendingReview,suggestedNextAction:input.suggestedNextAction});return db.transaction(()=>{db.prepare("INSERT INTO agent_runs VALUES (?,?,?,?,?,?,?)").run(rid,w.id,"Resident Wiki Agent","Generate continuity briefing",output,"completed",ts);db.prepare(`INSERT INTO workspace_briefings VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id) DO UPDATE SET current_focus=excluded.current_focus,recent_changes_json=excluded.recent_changes_json,blockers_json=excluded.blockers_json,pending_review_json=excluded.pending_review_json,suggested_next_action=excluded.suggested_next_action,generated_at=excluded.generated_at,agent_run_id=excluded.agent_run_id`).run(w.id,input.currentFocus,JSON.stringify(input.recentChanges),JSON.stringify(input.blockers),JSON.stringify(input.pendingReview),input.suggestedNextAction,ts,rid);recordActivity({workspaceId:w.id,actor:"wiki-agent",source:"wiki_agent",action:"briefing_generated",entityType:"workspace",entityId:w.id,summary:"Generated workspace briefing"});return getWorkspaceBriefing(w.id)!})()}
